language: node_js
node_js:
  - node
sudo: required
branches:
  only:
    - master
    - ci-test
install:
  - npm install
script:
  - npm run build
before_deploy:
  - openssl aes-256-cbc -K $encrypted_d11afb7726ff_key -iv $encrypted_d11afb7726ff_iv
    -in id_rsa.enc -out id_rsa -d
  - mv id_rsa ~/.ssh
  - chmod 600 ~/.ssh/id_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./script deploy.sh
addons:
  ssh_known_hosts:
    - '$DEPLOY_HOST'
